"""Install the Caucus hub as a per-user background service.

The hub is the only stateful process in Caucus, and every connector assumes it
is already listening: when it is not, the bridge answers ``hub_unreachable`` and
the operator has to go start it by hand. This module removes that step by
defining the hub as a service the platform's own supervisor owns.

Two modes, and the default is the unusual one:

- **On demand** (default) -- the service is *defined and loaded*, but nothing
  starts it at login. A ``SessionStart`` hook on the MCP host asks the service
  manager for it when an agent session actually opens. Caucus is used in bursts
  and hub state is ephemeral anyway, so a process idling for days earns nothing.
- **At login** (``--at-login``) -- the classic always-on daemon.

The hook deliberately asks the *service manager* to start an already-defined
service rather than spawning ``caucus-hub`` itself. ``nohup caucus-hub &`` would
race for the port when several sessions start at once, leave the surviving
process owned by whichever session won, and never restart after a crash;
``launchctl kickstart`` and ``systemctl --user start`` are idempotent and
serialised on the service identity for free.

Nothing here needs root, and nothing is written outside the user's home
directory. The console script ``caucus-setup-service`` (see
``[project.scripts]``) exposes :func:`main`, so a human or an agent over Bash
drives the same pipeline. It follows :mod:`caucus.automode`'s shape: describe
the change, ask, then write atomically with a backup.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Literal

DEFAULT_LABEL = "com.github.obeone.caucus-hub"
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8765
SYSTEMD_UNIT_NAME = "caucus-hub.service"

#: Marks the hook entry this module owns, so a re-run updates its own line
#: instead of appending a second one, and leaves the operator's hooks alone.
HOOK_MARKER = "[caucus-mcp:hub-ensure]"

#: Hosts where the hub's unauthenticated-by-default agent API is defensible.
LOOPBACK_HOSTS = frozenset({"127.0.0.1", "localhost", "::1"})

#: Tokens land in an XML plist and in a shell-sourced env file. Rather than
#: escaping for both, restrict them to characters neither treats specially;
#: every sane generator (``openssl rand -hex``, ``uuidgen``, base64url) fits.
TOKEN_RE = re.compile(r"^[A-Za-z0-9._~-]+$")

Platform = Literal["launchd", "systemd"]


LAUNCHD_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by caucus-setup-service. Re-run it rather than editing here. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>{label}</string>

  <!-- The no-browser flag below is not optional: without it the hub opens the
       operator console on every start, which as a service means a browser
       window at every login and after every automatic restart.
       (Written without leading dashes on purpose: a double dash is illegal
       inside an XML comment, and strict parsers reject the whole file.) -->
  <key>ProgramArguments</key>
  <array>
    <string>{binary}</string>
    <string>--host</string>
    <string>{host}</string>
    <string>--port</string>
    <string>{port}</string>
    <string>--no-browser</string>
  </array>

  <!-- Tokens live here rather than on the command line so they stay out of
       `ps` output. This file is written with mode 0600. -->
  <key>EnvironmentVariables</key>
  <dict>
{environment}  </dict>

  <!-- false in on-demand mode: the service is loaded at login but stays idle
       until the SessionStart hook kickstarts it. -->
  <key>RunAtLoad</key>
  <{run_at_load}/>

  <!-- Restart on crash, but not on a clean exit: a restart wipes the hub's
       in-memory state, so every peer loses its token and must join again. -->
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>10</integer>

  <key>StandardOutPath</key>
  <string>{logfile}</string>
  <key>StandardErrorPath</key>
  <string>{logfile}</string>

  <key>ProcessType</key>
  <string>Background</string>
</dict>
</plist>
"""


SYSTEMD_TEMPLATE = """\
# Generated by caucus-setup-service. Re-run it rather than editing here.
[Unit]
Description=Caucus hub (supervised agent message hub)
Documentation=https://github.com/obeone/caucus-mcp
After=network.target

[Service]
Type=simple

# Optional on purpose: the leading `-` means the unit still starts when the
# file is absent. Holds CAUCUS_OPERATOR_TOKEN and friends, kept out of the unit
# file and out of `ps`. Written with mode 0600.
EnvironmentFile=-{envfile}

# --no-browser is not optional: without it the hub tries to open the operator
# console on every start and after every automatic restart.
ExecStart={binary} --host {host} --port {port} --no-browser

# Restart on crash, but not on a clean exit: a restart wipes the hub's
# in-memory state, so every peer loses its token and must join again.
Restart=on-failure
RestartSec=10

StandardOutput=append:{logfile}
StandardError=append:{logfile}

# Modest hardening. Deliberately no ProtectHome: the hub's own JSONL disk log
# (CAUCUS_LOG_FILE) usually lives under $HOME, and a read-only home would turn
# that into a silent write failure. ProtectSystem=strict leaves $HOME writable.
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ProtectKernelTunables=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes

[Install]
WantedBy=default.target
"""


class SetupError(Exception):
    """A precondition failed, with a message meant for the operator."""


def detect_platform() -> Platform:
    """Return the service manager to target on this machine.

    Returns:
        ``"launchd"`` on macOS, ``"systemd"`` on Linux.

    Raises:
        SetupError: On any other platform, where neither applies.
    """
    system = platform.system()
    if system == "Darwin":
        return "launchd"
    if system == "Linux":
        return "systemd"
    raise SetupError(
        f"unsupported platform: {system}. Run `caucus-hub` yourself, or see "
        "docs/running-as-a-service.md for the templates."
    )


def unit_path(kind: Platform, label: str = DEFAULT_LABEL) -> Path:
    """Return where the service definition belongs for ``kind``.

    Args:
        kind: Service manager, from :func:`detect_platform`.
        label: Service identifier; only used by launchd, whose file name is the
            label.

    Returns:
        Path to the plist or unit file, inside the user's home.
    """
    if kind == "launchd":
        return Path.home() / "Library" / "LaunchAgents" / f"{label}.plist"
    config = Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")
    return config / "systemd" / "user" / SYSTEMD_UNIT_NAME


def default_log_path(kind: Platform) -> Path:
    """Return the conventional location for the service's stdout and stderr."""
    if kind == "launchd":
        return Path.home() / "Library" / "Logs" / "caucus-hub.log"
    state = Path(os.environ.get("XDG_STATE_HOME") or Path.home() / ".local" / "state")
    return state / "caucus" / "hub.log"


def env_file_path() -> Path:
    """Return the systemd ``EnvironmentFile`` path holding the operator tokens."""
    config = Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")
    return config / "caucus" / "hub.env"


def resolve_binary(explicit: str | None = None) -> Path:
    """Resolve an absolute path to the ``caucus-hub`` executable.

    Service managers do not inherit an interactive shell's ``PATH``, so the
    path has to be pinned at install time rather than looked up at start time.

    Args:
        explicit: Operator-supplied path, or ``None`` to search ``PATH``.

    Returns:
        Absolute path to an executable ``caucus-hub``.

    Raises:
        SetupError: When nothing usable is found, with the install command to
            run.
    """
    if explicit:
        candidate = Path(explicit).expanduser().resolve()
        if not candidate.is_file() or not os.access(candidate, os.X_OK):
            raise SetupError(f"not an executable file: {candidate}")
        return candidate

    found = shutil.which("caucus-hub")
    if not found:
        # Fall back to the interpreter running this module: an install done
        # with pipx or uv frequently leaves the scripts next to it, even when
        # that directory is absent from a non-interactive PATH.
        sibling = Path(sys.executable).parent / "caucus-hub"
        if sibling.is_file() and os.access(sibling, os.X_OK):
            return sibling.resolve()
        raise SetupError(
            "could not find caucus-hub on your PATH.\n"
            "Install it first:  uv tool install caucus-mcp\n"
            "Or point at it:    caucus-setup-service --binary /path/to/caucus-hub"
        )
    return Path(found).resolve()


def validate_tokens(operator: str | None, observer: str | None) -> None:
    """Reject tokens carrying characters that would need escaping downstream.

    Args:
        operator: Read-write dashboard token, or ``None``.
        observer: Read-only dashboard token, or ``None``.

    Raises:
        SetupError: When either token contains anything outside
            :data:`TOKEN_RE`.
    """
    for name, value in (("--operator-token", operator), ("--observer-token", observer)):
        if value is not None and not TOKEN_RE.match(value):
            raise SetupError(
                f"{name} may only contain letters, digits and . _ ~ -\n"
                "Generate one with:  openssl rand -hex 24"
            )


def check_port(port: int) -> None:
    """Reject a port the hub could never bind.

    Args:
        port: Requested TCP port.

    Raises:
        SetupError: When outside the unprivileged, bindable range. Ports below
            1024 need privileges this deliberately-unprivileged service will
            never have.
    """
    if not 1024 <= port <= 65535:
        raise SetupError(
            f"--port must be between 1024 and 65535, got {port}"
            + (
                "\nPorts below 1024 need root, and this is a per-user service."
                if port < 1024
                else ""
            )
        )


def check_bind(host: str, operator_token: str | None) -> None:
    """Refuse a network-visible bind that nobody can be kept out of.

    The hub serves its agent API unauthenticated by default, which is
    defensible precisely because it binds to loopback. Bound wider, any browser
    that reaches the port gets full operator rights: pause, stop, kick.

    Args:
        host: Address the hub would bind to.
        operator_token: Token that would gate operator access, if any.

    Raises:
        SetupError: For a non-loopback host with no operator token.
    """
    if host in LOOPBACK_HOSTS or operator_token:
        return
    raise SetupError(
        f"refusing to bind {host} without --operator-token.\n"
        "On a non-loopback address the dashboard accepts any browser that can\n"
        "reach it, with full operator rights. Keep 127.0.0.1, or run:\n"
        f'  caucus-setup-service --host {host} '
        '--operator-token "$(openssl rand -hex 24)"'
    )


def render_unit(
    *,
    kind: Platform,
    binary: Path,
    host: str,
    port: int,
    logfile: Path,
    label: str = DEFAULT_LABEL,
    at_login: bool = False,
    operator_token: str | None = None,
    observer_token: str | None = None,
) -> str:
    """Render the service definition for ``kind``.

    Args:
        kind: Service manager to target.
        binary: Absolute path to ``caucus-hub``.
        host: Bind address.
        port: Bind port.
        logfile: Where the supervisor sends stdout and stderr.
        label: Service identifier (launchd only).
        at_login: Start with the user session instead of on demand.
        operator_token: Embedded in the plist; systemd reads it from
            :func:`env_file_path` instead.
        observer_token: Same treatment as ``operator_token``.

    Returns:
        The complete file contents, ready to write.
    """
    if kind == "systemd":
        return SYSTEMD_TEMPLATE.format(
            binary=binary,
            host=host,
            port=port,
            logfile=logfile,
            envfile=env_file_path(),
        )

    environment = ""
    for name, value in (
        ("CAUCUS_OPERATOR_TOKEN", operator_token),
        ("CAUCUS_OBSERVER_TOKEN", observer_token),
    ):
        if value:
            environment += f"    <key>{name}</key>\n    <string>{value}</string>\n"

    return LAUNCHD_TEMPLATE.format(
        label=label,
        binary=binary,
        host=host,
        port=port,
        logfile=logfile,
        environment=environment,
        run_at_load="true" if at_login else "false",
    )


def hook_command(kind: Platform, label: str = DEFAULT_LABEL) -> str:
    """Return the shell command a ``SessionStart`` hook should run.

    Asks the service manager to start an already-defined service. Both forms
    are no-ops when the hub is already up, and neither restarts a running hub:
    ``launchctl kickstart`` is used *without* ``-k``, which would kill and
    relaunch, dropping every connected peer's token.

    Args:
        kind: Service manager to target.
        label: Service identifier (launchd only).

    Returns:
        A single shell command, ending in the idempotence marker so a re-run
        can find and update its own hook entry.
    """
    if kind == "launchd":
        action = f"launchctl kickstart gui/{os.getuid()}/{label}"
    else:
        action = f"systemctl --user start {SYSTEMD_UNIT_NAME}"
    return f"{action} >/dev/null 2>&1 || true  # {HOOK_MARKER}"


def _atomic_write(path: Path, text: str, *, mode: int = 0o600) -> None:
    """Write ``text`` to ``path`` atomically, with a backup of any prior file.

    Writes to a temp file in the same directory, fsyncs, then ``os.replace``
    onto the target, so a reader never sees a half-written file.

    Args:
        path: Destination. Its parent is created when missing.
        text: Full file contents.
        mode: Permission bits for the result; 0600 by default because these
            files can carry tokens.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") != text:
        shutil.copy2(path, path.with_suffix(path.suffix + ".bak"))

    fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=".caucus-", suffix=".tmp")
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        os.chmod(tmp, mode)
        os.replace(tmp, path)
    finally:
        with contextlib.suppress(FileNotFoundError):
            tmp.unlink()


def _atomic_write_json(path: Path, data: dict[str, Any]) -> None:
    """Write ``data`` as pretty JSON through :func:`_atomic_write`."""
    _atomic_write(path, json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def settings_path(project_dir: Path | None = None) -> Path:
    """Return the settings file the ``SessionStart`` hook belongs in.

    The hub is a machine-wide service, not a per-project one, so the hook
    defaults to the user baseline. Passing ``project_dir`` scopes it to a
    single checkout instead.

    Args:
        project_dir: Project root to scope the hook to, or ``None`` for the
            user baseline.

    Returns:
        Path to ``~/.claude/settings.json``, or the project's
        ``.claude/settings.local.json``.
    """
    if project_dir is not None:
        return project_dir / ".claude" / "settings.local.json"
    return Path.home() / ".claude" / "settings.json"


def hook_status(path: Path, command: str) -> Literal["absent", "current", "stale"]:
    """Report what the settings file already holds for our hook.

    Args:
        path: Settings file to inspect.
        command: The command we would install.

    Returns:
        ``"current"`` when our hook is present and identical, ``"stale"`` when
        present but different (a port change, say), ``"absent"`` otherwise.
        Unreadable or malformed files read as ``"absent"``.
    """
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return "absent"
    if not isinstance(data, dict):
        return "absent"

    for entry in _iter_session_start_hooks(data):
        existing = entry.get("command")
        if isinstance(existing, str) and HOOK_MARKER in existing:
            return "current" if existing == command else "stale"
    return "absent"


def _iter_session_start_hooks(data: dict[str, Any]) -> list[dict[str, Any]]:
    """Return every ``SessionStart`` command entry in a settings mapping.

    Tolerates the shapes a hand-edited settings file can be in: missing keys,
    wrong types, matcher groups without a ``hooks`` list. Anything unexpected
    is skipped rather than raising, since this runs against files we did not
    write.

    Args:
        data: Parsed settings mapping.

    Returns:
        The individual hook dicts, flattened across matcher groups.
    """
    hooks = data.get("hooks")
    if not isinstance(hooks, dict):
        return []
    groups = hooks.get("SessionStart")
    if not isinstance(groups, list):
        return []

    entries: list[dict[str, Any]] = []
    for group in groups:
        if not isinstance(group, dict):
            continue
        inner = group.get("hooks")
        if not isinstance(inner, list):
            continue
        entries.extend(item for item in inner if isinstance(item, dict))
    return entries


def apply_hook(path: Path, command: str) -> dict[str, object]:
    """Install or refresh the ``SessionStart`` hook in ``path``.

    Idempotent, and surgical: an existing entry carrying :data:`HOOK_MARKER` is
    updated in place, so a re-run after a port change does not accumulate a
    second hook. Every other key, and every hook the operator wrote, is
    preserved. A ``.bak`` copy is left behind before replacing.

    Args:
        path: Settings file to modify. Created when missing.
        command: Shell command the hook should run.

    Returns:
        A mapping with ``changed`` (whether anything was written), ``path``,
        and ``action`` (``"created"``, ``"updated"`` or ``"unchanged"``).
    """
    status = hook_status(path, command)
    if status == "current":
        return {"changed": False, "path": str(path), "action": "unchanged"}

    data: dict[str, Any] = {}
    if path.exists():
        try:
            loaded = json.loads(path.read_text(encoding="utf-8"))
            if isinstance(loaded, dict):
                data = loaded
        except (OSError, json.JSONDecodeError) as exc:
            raise SetupError(
                f"{path} is not valid JSON, refusing to overwrite it: {exc}"
            ) from exc

    if status == "stale":
        for entry in _iter_session_start_hooks(data):
            existing = entry.get("command")
            if isinstance(existing, str) and HOOK_MARKER in existing:
                entry["command"] = command
        _atomic_write_json(path, data)
        return {"changed": True, "path": str(path), "action": "updated"}

    hooks = data.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        raise SetupError(f'{path} has a non-object "hooks" key, refusing to touch it')
    groups = hooks.setdefault("SessionStart", [])
    if not isinstance(groups, list):
        raise SetupError(f'{path} has a non-list "SessionStart", refusing to touch it')
    groups.append({"hooks": [{"type": "command", "command": command}]})

    action = "created" if not path.exists() else "updated"
    _atomic_write_json(path, data)
    return {"changed": True, "path": str(path), "action": action}


def write_env_file(operator: str | None, observer: str | None) -> Path | None:
    """Write the systemd token file, or return ``None`` when there is nothing to.

    Args:
        operator: Read-write dashboard token, or ``None``.
        observer: Read-only dashboard token, or ``None``.

    Returns:
        The path written, or ``None`` when no token was supplied.
    """
    if not operator and not observer:
        return None
    path = env_file_path()
    lines = ["# Written by caucus-setup-service. Read by the systemd user unit."]
    if operator:
        lines.append(f"CAUCUS_OPERATOR_TOKEN={operator}")
    if observer:
        lines.append(f"CAUCUS_OBSERVER_TOKEN={observer}")
    _atomic_write(path, "\n".join(lines) + "\n")
    return path


def load_service(kind: Platform, path: Path, *, at_login: bool, label: str) -> None:
    """Register the service with the platform supervisor and start it once.

    Starting it here is not the same as starting it at login: it proves the
    definition actually works, which is worth more than the seconds it costs.

    Args:
        kind: Service manager to target.
        path: The unit or plist just written.
        at_login: Whether the service should also come up with the session.
        label: Service identifier (launchd only).

    Raises:
        SetupError: When the supervisor rejects the definition.
    """
    uid = os.getuid()
    try:
        if kind == "launchd":
            # bootout first so a re-run picks up the new definition; it fails
            # harmlessly when nothing is loaded yet.
            subprocess.run(
                ["launchctl", "bootout", f"gui/{uid}/{label}"],
                capture_output=True,
                check=False,
            )
            subprocess.run(
                ["launchctl", "bootstrap", f"gui/{uid}", str(path)],
                capture_output=True,
                check=True,
            )
            subprocess.run(
                ["launchctl", "kickstart", "-k", f"gui/{uid}/{label}"],
                capture_output=True,
                check=True,
            )
        else:
            subprocess.run(
                ["systemctl", "--user", "daemon-reload"], capture_output=True, check=True
            )
            enable = "enable" if at_login else "disable"
            # Not enabled means not wired to default.target, so nothing starts
            # it at login; the explicit restart below still brings it up now.
            subprocess.run(
                ["systemctl", "--user", enable, SYSTEMD_UNIT_NAME],
                capture_output=True,
                check=False,
            )
            subprocess.run(
                ["systemctl", "--user", "restart", SYSTEMD_UNIT_NAME],
                capture_output=True,
                check=True,
            )
    except FileNotFoundError as exc:  # pragma: no cover - platform mismatch
        raise SetupError(f"service manager not available: {exc}") from exc
    except subprocess.CalledProcessError as exc:
        detail = (exc.stderr or b"").decode("utf-8", "replace").strip()
        raise SetupError(f"{' '.join(exc.cmd)} failed: {detail or exc.returncode}") from exc


def probe(host: str, port: int, *, attempts: int = 10) -> bool:
    """Poll the hub's ``/version`` until it answers, or give up.

    ``/version`` is the cheapest open endpoint. Not ``/ping``, which reports on
    a *peer* and needs a ``peer`` parameter, and there is no HTTP ``/health``.

    Args:
        host: Address the hub was bound to; wildcards are probed on loopback.
        port: Bind port.
        attempts: How many one-second tries before returning ``False``.

    Returns:
        Whether the hub answered.
    """
    probe_host = {"0.0.0.0": "127.0.0.1", "::": "::1"}.get(host, host)
    bracket = f"[{probe_host}]" if ":" in probe_host else probe_host
    url = f"http://{bracket}:{port}/version"
    for attempt in range(attempts):
        try:
            with urllib.request.urlopen(url, timeout=2):  # noqa: S310 - fixed http URL
                return True
        except (urllib.error.URLError, OSError):
            if attempt < attempts - 1:
                time.sleep(1)
    return False


def describe_plan(
    *,
    kind: Platform,
    binary: Path,
    host: str,
    port: int,
    logfile: Path,
    unit: Path,
    at_login: bool,
    operator_token: str | None,
    hook_path: Path | None,
    hook_action: str,
) -> str:
    """Build the human-readable summary shown before anything is written.

    Args:
        kind: Service manager being targeted.
        binary: Resolved ``caucus-hub`` path.
        host: Bind address.
        port: Bind port.
        logfile: Where stdout and stderr will go.
        unit: The unit or plist that will be written.
        at_login: Whether the hub will start with the session.
        operator_token: Present when dashboard access will be gated.
        hook_path: Settings file the hook goes into, or ``None`` when the
            operator declined it.
        hook_action: What would happen to that file.

    Returns:
        A multi-line block, ending without a trailing newline.
    """
    starts = (
        "at login, and stays up"
        if at_login
        else "on demand, when an agent session opens"
    )
    lines = [
        "",
        f"Caucus hub as a {kind} service. Here is what will happen:",
        "",
        f"  write    {unit}",
        f"           runs {binary} on {host}:{port}, logging to {logfile}",
        f"  starts   {starts}",
        f"  access   {'operator token required' if operator_token else 'open (loopback only)'}",
    ]
    if hook_path is not None:
        verb = {"created": "create", "updated": "update", "unchanged": "leave"}
        lines.append(
            f"  hook     {verb.get(hook_action, 'update')} {hook_path}"
            f" ({'already current' if hook_action == 'unchanged' else 'SessionStart'})"
        )
    lines += [
        "",
        "No sudo, nothing outside your home directory. Undo it all with",
        "`caucus-setup-service --uninstall`.",
        "",
        "One thing worth knowing: restarting the hub clears its in-memory state,",
        "so connected peers lose their tokens and have to join again.",
    ]
    return "\n".join(lines)


def confirm(prompt: str = "Proceed?") -> bool:
    """Ask the operator to approve, defaulting to no.

    A non-interactive stdin (a pipe, an agent's Bash tool) cannot answer, so it
    is treated as a refusal rather than as consent.

    Args:
        prompt: Question to show.

    Returns:
        Whether the operator typed yes.
    """
    if not sys.stdin.isatty():
        print(
            f"\n{prompt} stdin is not a terminal, so nothing was changed.\n"
            "Re-run with --yes to proceed without asking.",
            file=sys.stderr,
        )
        return False
    try:
        answer = input(f"\n{prompt} [y/N] ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return False
    return answer in {"y", "yes"}


def uninstall(kind: Platform, label: str = DEFAULT_LABEL) -> dict[str, object]:
    """Stop the service and remove its definition.

    Leaves the log file, the token file and the ``SessionStart`` hook alone:
    they are cheap to remove by hand and expensive to delete by surprise.

    Args:
        kind: Service manager to target.
        label: Service identifier (launchd only).

    Returns:
        A mapping with ``removed`` and the ``path`` that was targeted.
    """
    path = unit_path(kind, label)
    uid = os.getuid()
    if kind == "launchd":
        subprocess.run(
            ["launchctl", "bootout", f"gui/{uid}/{label}"],
            capture_output=True,
            check=False,
        )
    else:
        subprocess.run(
            ["systemctl", "--user", "disable", "--now", SYSTEMD_UNIT_NAME],
            capture_output=True,
            check=False,
        )
    existed = path.exists()
    with contextlib.suppress(FileNotFoundError):
        path.unlink()
    if kind == "systemd":
        subprocess.run(
            ["systemctl", "--user", "daemon-reload"], capture_output=True, check=False
        )
    return {"removed": existed, "path": str(path)}


def _build_parser() -> argparse.ArgumentParser:
    """Build the ``caucus-setup-service`` argument parser."""
    parser = argparse.ArgumentParser(
        prog="caucus-setup-service",
        description=(
            "Install the Caucus hub as a per-user background service. No sudo, "
            "nothing written outside your home directory."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "By default the hub starts on demand: the service is defined but "
            "idle until a\nSessionStart hook asks for it. Pass --at-login to "
            "keep it running instead."
        ),
    )
    parser.add_argument("--host", default=DEFAULT_HOST, help="bind address")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT, help="bind port")
    parser.add_argument("--binary", help="path to caucus-hub (default: found on PATH)")
    parser.add_argument("--label", default=DEFAULT_LABEL, help="service identifier")
    parser.add_argument("--log-file", help="where the service writes stdout and stderr")
    parser.add_argument(
        "--operator-token", help="require this token for read-write dashboard access"
    )
    parser.add_argument(
        "--observer-token", help="token for read-only dashboard access"
    )
    parser.add_argument(
        "--at-login",
        action="store_true",
        help="start the hub at login and keep it up, instead of on demand",
    )
    parser.add_argument(
        "--no-hook",
        action="store_true",
        help="do not touch settings.json (you wire the SessionStart hook yourself)",
    )
    parser.add_argument(
        "--project",
        help="scope the hook to this project instead of your user settings",
    )
    parser.add_argument(
        "--yes", "-y", action="store_true", help="do not ask for confirmation"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print the plan and the generated unit, change nothing",
    )
    parser.add_argument(
        "--uninstall", action="store_true", help="stop the service and remove it"
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """Entry point for ``caucus-setup-service``.

    Args:
        argv: Command line, or ``None`` to read ``sys.argv``.

    Returns:
        Process exit status: 0 on success, 1 on a failed precondition or a hub
        that never answered, 2 when the operator declined.
    """
    args = _build_parser().parse_args(argv)

    try:
        kind = detect_platform()

        if os.getuid() == 0:
            raise SetupError("refusing to run as root: this installs a per-user service")

        if args.uninstall:
            result = uninstall(kind, args.label)
            if result["removed"]:
                print(f"Removed {result['path']}")
            else:
                print(f"Nothing to remove at {result['path']}")
            print("Your log file, token file and SessionStart hook were left alone.")
            return 0

        validate_tokens(args.operator_token, args.observer_token)
        check_port(args.port)
        check_bind(args.host, args.operator_token)
        binary = resolve_binary(args.binary)
        logfile = (
            Path(args.log_file).expanduser() if args.log_file else default_log_path(kind)
        )
        unit = unit_path(kind, args.label)
        rendered = render_unit(
            kind=kind,
            binary=binary,
            host=args.host,
            port=args.port,
            logfile=logfile,
            label=args.label,
            at_login=args.at_login,
            operator_token=args.operator_token,
            observer_token=args.observer_token,
        )

        command = hook_command(kind, args.label)
        hook_path: Path | None = None
        hook_action = "unchanged"
        if not args.no_hook and not args.at_login:
            project = Path(args.project).expanduser() if args.project else None
            hook_path = settings_path(project)
            hook_action = {
                "absent": "created" if not hook_path.exists() else "updated",
                "stale": "updated",
                "current": "unchanged",
            }[hook_status(hook_path, command)]

        print(
            describe_plan(
                kind=kind,
                binary=binary,
                host=args.host,
                port=args.port,
                logfile=logfile,
                unit=unit,
                at_login=args.at_login,
                operator_token=args.operator_token,
                hook_path=hook_path,
                hook_action=hook_action,
            )
        )

        if args.dry_run:
            print(f"\n--- {unit} ---\n{rendered}--- end (dry run) ---")
            if hook_path is not None:
                print(f"\n--- SessionStart hook in {hook_path} ---\n{command}")
            return 0

        if not args.yes and not confirm():
            print("Nothing was changed.")
            return 2

        _atomic_write(unit, rendered)
        if kind == "systemd":
            write_env_file(args.operator_token, args.observer_token)
        if hook_path is not None:
            apply_hook(hook_path, command)
        load_service(kind, unit, at_login=args.at_login, label=args.label)

        if not probe(args.host, args.port):
            print(
                f"\nInstalled, but the hub did not answer on {args.host}:{args.port}.\n"
                f"Check the log:  tail -n 50 {logfile}",
                file=sys.stderr,
            )
            return 1

        print(f"\nHub is up: http://{args.host}:{args.port}/")
        print(f"Logs: {logfile}")
        if not args.at_login and hook_path is None:
            print(
                "\nNothing will start it after a reboot: wire up the SessionStart "
                f"hook yourself with\n  {command}"
            )
        return 0

    except SetupError as exc:
        print(f"\n{exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":  # pragma: no cover - console-script shim
    raise SystemExit(main())
